### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by hfxunlp** [JiaBob/Sentence-alignment#1]
Hi, I need to align sentences between two documents, could you please help me with how to use your toolkit?

**Comment by JiaBob** [comment]
Hi,dude. In this version, I haven't supported the command line operation. Thus, you can import it in your python script. SAbyCN.py or SAbyPT.py is the scripts which is used for sentence alignment. Just see the code at the bottom, you will know how to use them.

**Comment by hfxunlp** [comment]
Thank you for your help, I will try it. @JiaBob

**Comment by hfxunlp** [comment]
Another word, If you want to make it a cmd tool, just `import sys` and use `sys.argv` will be ok. It was not a big change.
